package bo.edu.ucbcba.hotel.view;
import bo.edu.ucbcba.hotel.controller.SalonReservationController;
import bo.edu.ucbcba.hotel.model.SalonReservation;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by Gabo on 26-Jun-16.
 */
public class TypeOfReservationForm extends JDialog {
    private JPanel TypeReservationPanel;
    private JButton roomReservationButton;
    private JButton salonReservationButton;

    TypeOfReservationForm(JFrame parent) {
        super(parent, "Type of reservation", true);
        pack();
        setContentPane(TypeReservationPanel);
        setBounds(500, 250, 550, 180);
        salonReservationButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                salonreservatio();
            }
        });

    }

    private void salonreservatio() {
        SalonReservationForm salonReservationForm = new SalonReservationForm(this);
        salonReservationForm.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        TypeReservationPanel = new JPanel();
        TypeReservationPanel.setLayout(new GridLayoutManager(3, 3, new Insets(10, 10, 10, 10), -1, -1));
        roomReservationButton = new JButton();
        roomReservationButton.setText("Room Reservation");
        TypeReservationPanel.add(roomReservationButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(104, 32), null, 0, false));
        final Spacer spacer1 = new Spacer();
        TypeReservationPanel.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(104, 14), null, 0, false));
        salonReservationButton = new JButton();
        salonReservationButton.setText("Salon Reservation");
        TypeReservationPanel.add(salonReservationButton, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Choose Type of Reservation");
        TypeReservationPanel.add(label1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return TypeReservationPanel;
    }
}
